import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@/Components/button/button'
import { useRouter } from 'next/router'
import style from 'styles/userInfo.module.css'
import { getFeaturedEvents } from '@/Api/Api'
import EventsList from '@/Components/Event-list/Events-list'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Cozy4real</h1>

        <ul>

          <Button link={'about'} children='about'/>
          <Button link={'userInfo'} children='Events'/>
        </ul>

        <ul className={style.list}>        
            
            {
                props.featuredEvents.map((item) => {
                    return (
                        <EventsList {...item}/>
                    )
                })
            }
        </ul>

      </main>
    </>
  )
}

export async function getStaticProps(context){
  const featuredEvents = await getFeaturedEvents()

  return {
      props: {
          featuredEvents : featuredEvents
      },
      revalidate: 1800
  }
}
